import i18next, { type i18n as I18n } from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
import { applyDirection } from './direction';
import { LANGUAGES, isSupportedLanguage, type LanguageCode } from './languages';
import en from '../locales/en/translation.json';

/**
 * i18n bootstrap.
 *
 * Conventions (see docs/I18N.md):
 * - Keys are the English source text: `t('Add monitor')`. The `en` catalogue
 *   maps each key to itself and is generated by `npm run i18n:extract`, so a
 *   missing translation always falls back to readable English, never a key.
 * - One namespace (`translation`), no key/namespace separators — so English
 *   text containing `.` or `:` is a valid key.
 * - Catalogues live in `src/locales/<lang>/translation.json` and load lazily
 *   per language (one chunk each); `en` is bundled.
 * - Direction follows the language: `applyDirection()` sets `<html dir>` and
 *   `lang` on every change. Layout uses logical CSS so RTL needs no per-
 *   component work; physical media (video, timelines, PTZ) opt out with
 *   `dir="ltr"`.
 */

const catalogues = import.meta.glob<{ default: Record<string, string> }>(
  '../locales/*/translation.json',
);

async function loadCatalogue(lng: string): Promise<Record<string, string> | null> {
  const loader = catalogues[`../locales/${lng}/translation.json`];
  if (!loader) return null;
  return (await loader()).default;
}

export const DEFAULT_LANGUAGE: LanguageCode = 'en';
export const LANGUAGE_STORAGE_KEY = 'zm-lang';

/**
 * Load a language's catalogue into `instance` if it exists and is not loaded
 * yet. Returns true when something was added. `en` is bundled at init.
 */
async function ensureLoaded(instance: I18n, lng: string): Promise<boolean> {
  const base = lng.split('-')[0];
  let added = false;
  for (const code of new Set([lng, base])) {
    if (code === DEFAULT_LANGUAGE) continue;
    if (instance.hasResourceBundle(code, 'translation')) continue;
    const bundle = await loadCatalogue(code);
    if (bundle) {
      instance.addResourceBundle(code, 'translation', bundle, true, true);
      added = true;
    }
  }
  return added;
}

export function setupI18n(instance: I18n = i18next): I18n {
  if (instance.isInitialized) return instance;

  // Register before init(): with bundled resources i18next emits the first
  // `languageChanged` synchronously inside init(), and a listener attached
  // afterwards would miss it (the document would stay ltr for Hebrew).
  instance.on('languageChanged', (lng) => applyDirection(lng));

  instance
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      // `en` is bundled: it carries the English plural forms (`_one`/`_other`)
      // which the key text alone cannot express. Other languages load lazily.
      resources: { en: { translation: en } },
      fallbackLng: DEFAULT_LANGUAGE,
      supportedLngs: LANGUAGES.map((l) => l.code),
      nonExplicitSupportedLngs: true,
      load: 'currentOnly',
      ns: ['translation'],
      defaultNS: 'translation',
      keySeparator: false,
      nsSeparator: false,
      returnEmptyString: false,
      interpolation: { escapeValue: false }, // React escapes
      detection: {
        order: ['querystring', 'localStorage', 'navigator'],
        lookupQuerystring: 'lang',
        lookupLocalStorage: LANGUAGE_STORAGE_KEY,
        caches: ['localStorage'],
      },
      react: { useSuspense: false },
    });

  // The detected language may have a catalogue on disk that is not loaded
  // yet; fetch it, then re-apply the language so `resolvedLanguage` and every
  // mounted `t()` pick up the translations.
  const initial = instance.language ?? DEFAULT_LANGUAGE;
  applyDirection(initial);
  void ensureLoaded(instance, initial).then((added) => {
    if (added) void instance.changeLanguage(initial);
  });

  return instance;
}

/** Switch language (persisted by the detector's localStorage cache). */
export async function changeLanguage(code: string): Promise<void> {
  if (!isSupportedLanguage(code)) throw new Error(`Unsupported language: ${code}`);
  await ensureLoaded(i18next, code); // catalogue first, so the switch renders translated
  await i18next.changeLanguage(code);
}

export { LANGUAGES, isSupportedLanguage } from './languages';
export type { LanguageCode } from './languages';

setupI18n();

export default i18next;
