/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MontagereviewIndexRouteImport } from './routes/montagereview/index'
import { Route as MontageIndexRouteImport } from './routes/montage/index'
import { Route as MonitorsIndexRouteImport } from './routes/monitors/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CycleIndexRouteImport } from './routes/cycle/index'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as MonitorsMonitorIdRouteImport } from './routes/monitors/$monitorId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontagereviewIndexRoute = MontagereviewIndexRouteImport.update({
  id: '/montagereview/',
  path: '/montagereview/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontageIndexRoute = MontageIndexRouteImport.update({
  id: '/montage/',
  path: '/montage/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsIndexRoute = MonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleIndexRoute = CycleIndexRouteImport.update({
  id: '/cycle/',
  path: '/cycle/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/settings/storage',
  path: '/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsMonitorIdRoute = MonitorsMonitorIdRouteImport.update({
  id: '/monitors/$monitorId',
  path: '/monitors/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/users': typeof SettingsUsersRoute
  '/cycle/': typeof CycleIndexRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/montage/': typeof MontageIndexRoute
  '/montagereview/': typeof MontagereviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/users': typeof SettingsUsersRoute
  '/cycle': typeof CycleIndexRoute
  '/events': typeof EventsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/monitors': typeof MonitorsIndexRoute
  '/montage': typeof MontageIndexRoute
  '/montagereview': typeof MontagereviewIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/users': typeof SettingsUsersRoute
  '/cycle/': typeof CycleIndexRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/montage/': typeof MontageIndexRoute
  '/montagereview/': typeof MontagereviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/events/$eventId'
    | '/monitors/$monitorId'
    | '/settings/storage'
    | '/settings/users'
    | '/cycle/'
    | '/events/'
    | '/groups/'
    | '/logs/'
    | '/monitors/'
    | '/montage/'
    | '/montagereview/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/events/$eventId'
    | '/monitors/$monitorId'
    | '/settings/storage'
    | '/settings/users'
    | '/cycle'
    | '/events'
    | '/groups'
    | '/logs'
    | '/monitors'
    | '/montage'
    | '/montagereview'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/events/$eventId'
    | '/monitors/$monitorId'
    | '/settings/storage'
    | '/settings/users'
    | '/cycle/'
    | '/events/'
    | '/groups/'
    | '/logs/'
    | '/monitors/'
    | '/montage/'
    | '/montagereview/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  MonitorsMonitorIdRoute: typeof MonitorsMonitorIdRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  CycleIndexRoute: typeof CycleIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MonitorsIndexRoute: typeof MonitorsIndexRoute
  MontageIndexRoute: typeof MontageIndexRoute
  MontagereviewIndexRoute: typeof MontagereviewIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montagereview/': {
      id: '/montagereview/'
      path: '/montagereview'
      fullPath: '/montagereview/'
      preLoaderRoute: typeof MontagereviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montage/': {
      id: '/montage/'
      path: '/montage'
      fullPath: '/montage/'
      preLoaderRoute: typeof MontageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/': {
      id: '/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof MonitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle/': {
      id: '/cycle/'
      path: '/cycle'
      fullPath: '/cycle/'
      preLoaderRoute: typeof CycleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/settings/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/$monitorId': {
      id: '/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof MonitorsMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  MonitorsMonitorIdRoute: MonitorsMonitorIdRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  CycleIndexRoute: CycleIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MonitorsIndexRoute: MonitorsIndexRoute,
  MontageIndexRoute: MontageIndexRoute,
  MontagereviewIndexRoute: MontagereviewIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
